### ISSUE TITLE
Error: Cannot find module './types'

### ISSUE THREAD

**Issue by D-32** [Psifi-Solutions/csrf-csrf#92]
When updating from 3.1.0 to 3.2.0 I'm now getting the following error:
```Error: Cannot find module './types'```

I double checked it's only since 3.2.0. Not using typescript myself in the project I'm using csrf-csrf in.

Thanks for your work! 🙏

**Comment by psibean** [comment]
Just pushed 3.2.1 to fix the botched release. 🤦🏻 

This keeps happening because the build config on v3 is really bad. It's all fixed up on the main branch, so it won't happen any more from v4 onwards.

This is likely going to be the last v3 release.

**Comment by psibean** [comment]
Ugh. 3.2.1 is worse. 🤦🏻

**Comment by psibean** [comment]
Yeah, false alarm, 3.2.1 should be good.

**Comment by D-32** [comment]
Perfect, thank you very much for the quick fix, appreciate it!
